<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Async-Await</title>
  </head>
  <body>
    <script>
      const wait = (ms = 0) =>
        new Promise((resolve) => setTimeout(resolve, ms));

      function makePizza(toppings = []) {
        return new Promise(function (resolve, reject) {
          // checking if pineapple is toppings
          if (toppings.includes("pineapple")) {
            reject("Seriously, Get Out üçç");
          }
          const amountOfTimeToBake = 500 + toppings.length * 200;
          // wait one second for pizza to bake
          setTimeout(function () {
            resolve(`Here is your pizza üçï with toppings ${toppings}.`);
          }, amountOfTimeToBake);
        });
      }

      function handleError(err) {
        console.log("Ohh Noo");
        console.log(err);
      }

      async function go() {
        // handling with the try / catch
        // try {
        //   const pizza = await makePizza(["pineapple"]);
        //   console.log(pizza);
        // } catch (err) {
        //   console.log("Oh Nooo");
        //   console.log(err);
        // }

        const pizza = await makePizza(["pineapple"]); // .catch(handleError);
        console.log(pizza);
      }

      // catch it at run time  async await returns a promise
      // go().catch(handleError);

      // error handling with Higher-Order Function
      function makeSafe(fn, errorHandler) {
        return function () {
          fn().catch(errorHandler);
        };
      }

      const safeGo = makeSafe(go, handleError);
      safeGo();
    </script>
  </body>
</html>
